components/contributors/GithubActivity.jsx

links in contribution timeline now break word if too long for viewport.
closes #10

fixed word wrap

---

components/contributors/GithubActivity.jsx

Handle `issue_closed` GitHub activity in renderText

---

lib/utils.js
pages/index.js

Closes #71 
- When a week completely falls in the same month:
- When a week belongs to two months:

Fix leaderboard static date range

---

components/filters/Filters.jsx
components/filters/IconToggle.jsx
components/filters/Sort.jsx
pages/leaderboard.js

Closes #73
The following changes were made:
- Excess spacing between the search bar and live leaderboard is reduced
- Search sort and toggle are placed in a single row in desktop and left justified in mobile view

UI enhancements for search, sort and toggle

---

scraper/src/github.py

The collaboration event entry was inside the for loop, which was creating multiple entries, moved it out

Fixed multiple entries of collaboration event

---

.env
README.md
components/Footer.jsx
components/Header.jsx
components/PageHead.jsx
pages/contributors/[slug].js
pages/index.js
yarn.lock

- Converted all customizable strings to env variables

Added strings to env file

---

components/contributors/InfoCard.jsx
components/contributors/LeaderboardCard.jsx
components/contributors/TopContributor.jsx
pages/contributors/[slug].js

avatars.githubusercontent.com has the appropriate CORS headers, so it should not fail on browsers with stricter CORS requirements

fix: github avatars not rendering on firefox

---

components/contributors/BadgeIcons.tsx

Fixes #128 
The badge label is visible in dark mode as well

Show Badge label in dark mode

---

components/ThemeSwitch.tsx

Fixes #130 
Removed the switch and used button instead. Made the default theme as dark
Dark:
Light:

Fix theme button in header

---

app/page.tsx
components/contributors/InfoCard.tsx
components/gh_events/GitHubEvent.tsx
components/gh_events/GitHubEvents.tsx
components/gh_events/OpenGraphImage.tsx
lib/api.ts
package.json
pnpm-lock.yaml

We have prettier config but we did have the packages installed, just installed them and did `pnpm lint -- --fix`

added prettier extensions and fixed related eslint errors

---

scraper/src/github.py

Use cache to prevent API rate limit on user scan

---

components/gh_events/GitHubEvent.tsx

fixes opengraph image not shown for PR close events

---

.prettierignore
app/contributors/[slug]/page.tsx

Pre-render contributor profile pages

---

app/contributors/[slug]/page.tsx
components/contributors/ActivityCalendarGitHub.tsx

The third-party activity calendar package causes builds to fail during the pre-rendering of contributors' pages. This was due to the following code in the third-party package.
- Force the activity calendar to render only in the browser.
- Fixes hydration warning with tooltip in currently working on (had `<div>` inside `<p>`)

Fixes hydration warnings and issue with pre-rendering activity calendar

---

app/contributors/[slug]/page.tsx

Last week highlights in contributor profile were not visible properly in light theme. Changed the color for white to foreground.
fixes #189

Made last week highlights of a contributor visible in light theme.

---

components/contributors/InfoCard.tsx

Closes #203 
Added `text-overflow`

Fix: Add text-overflow

---

app/api/leaderboard/functions.ts
app/api/leaderboard/route.ts
app/leaderboard/Leaderboard.tsx
app/leaderboard/page.tsx
components/contributors/LeaderboardCard.tsx
components/contributors/TopContributor.tsx
lib/utils.ts
package.json
pnpm-lock.yaml

**Before**
**After**
- Fixes #215

Adds API route `/leaderboard` and ✨ Optimize leaderboard page size

---

app/contributors/[slug]/page.tsx
app/page.tsx
app/projects/ActiveProjects.tsx
app/projects/constants.ts
app/projects/page.tsx
components/Markdown.tsx
components/RelativeTime.tsx
lib/utils.ts
package.json
pnpm-lock.yaml

- New environment variable added `GITHUB_PAT`. This token is required during the pre-rendering of Active Projects in order to make GraphQL calls to fetch issues at organization level.

Adds support for showing Active Projects

---

components/contributors/GithubActivity.tsx

In the dark mode setting, the select menu within the `GithubActivity.tsx` component was found to be unreadable due to insufficient contrast between the text color and the background. This issue was particularly noticeable in the `Filter Activity` section, where the select menu's text was merging with the dark background, making it hard for users to read the options available.
To address this issue, a commit was made to adjust the CSS class of the select menu. The change involved modifying the border color to ensure it remains consistent in both light and dark modes, thereby improving readability. Specifically, the CSS class was updated from:
```css
className="block px-2 py-1 rounded border border-gray-600 dark:border-gray-300 text-sm font-medium focus:z-10 focus:outline-none …
```

Fix Select Menu Unreadable in Dark Mode

---

app/page.tsx

Add a limit to 8 contributor info cards on the home page. Because it takes less time, and memory to reload and enhance the speed of the home page.
Fixes #237 
Make changes in the home page(page.tsx) the change will be while fetching data add slice on array till 8

home page users limit till 8 it

---

app/leaderboard/Leaderboard.tsx
components/DateRangePicker.tsx

Fixes this issue of overflowing in leaderboard by adjusting it with screen.
fix issue: #253

fix: fixes sorting container

---

load-org-data.sh

fixes - #334 
- Renamed remote name from origin to upsteam 
- Updated script to skip cloning if already cloned

Updated script to skip cloning if already cloned

---

scraper/src/github.py
scripts/migrations/002_migrate_github_activity_timestamps.js
scripts/migrations/003_migration_to_remove_duplicate_activities.js

fixes #324  
- Created a script for cleaning up existing data.
- Prevents duplicate events from getting merged.
linked pr:
https://github.com/coronasafe/leaderboard-data/pull/29

Prevents duplicate events from merging with existing events.

---

app/api/leaderboard/functions.ts
app/releases/page.tsx
lib/types.ts
package.json

This pull request addresses the issue by migrating the fetchGitHubReleases method to use Octokit instead of the traditional fetch to interact with GitHub APIs. I have made several modifications as follows:
- Utilized `Octokit.graphql` for interacting with GitHub API.
- Replaced the conventional for loop with a `flatMap`.
- Adjusted the `ReleasesResponse` type interface to align with the response type from Octokit GraphQL.
- Install `@octokit/graphql`
Fixes #347 
1. Integration of `Octokit.graphql` for GitHub API interaction.
2. Implementation of `flatMap` for improved efficiency.
3. Refactoring of `ReleasesResponse` interface to match Octokit GraphQL response structure.

Migrate fetchGitHubReleases Method to Use Octokit for GitHub API Interactions

---

components/gh_events/GitHubEvent.tsx

change review event text in github feed closes #362

---

components/contributors/BadgeIcons.tsx

fix #298 
Now badge popup has visual separation from the background
And badge levels are only green if that level was attained. Unobtained levels are gray / faded out
Before Changes -
After Changes-

fix: UI improvements to Contributor Badge Popup

---

.env
app/page.tsx
env.mjs

Implemented the following action items based on the provided issue statement:
1. Created an environment variable NEXT_PUBLIC_ORG_START_DATE.
2. Displayed the number of weeks since the configured start date on the home page.
3. Added functionality to show the organization's start date itself as a tooltip on hover.
Fixes #327 
Added `NEXT_PUBLIC_ORG_START_DATE` to the `.env` file.
Utilized `date-fns` library for updating the home route to calculate and display the required date information.

Add Organization Start Date Display and Tooltip with Total Weeks on Home Page

---

next.config.js

Fixes the issue where the period in the path will fail to match the github opengraph remotePatterns
this resulted in a crash on local:
and failed to generate image on deployment:
after fix:

fix github og images where repo starts with a period

---

scraper/src/github.py

Error: https://github.com/coronasafe/leaderboard-data/actions/runs/8258085927/job/22589738046
In certain cases, GitHub returns the event with `commit.author` being `null` and hence have to use the `commit.commit.author.name` instead.
<details>
<summary>Sample Response 1</summary>
```json
{
"sha": "b381289d451f9ea75879ccab892fa7db5adb4cde",
"node_id": "C_kwDOLdtyR9oAKGIzODEyODlkNDUxZjllYTc1ODc5Y2NhYjg5MmZhN2RiNWFkYjRjZGU",
"commit": {
"author": {
"name": "Dareenfadel",
"email": "https://github.com/Dareenfadel",
"date": "2024-03-08T21:57:06Z"
},
"committer": {
"name": "Dareenfadel",
"email": "https://github.com/Dareenfadel",
"date": "2024-03-08T21:57:06Z"
},
"message": "\"Fix issue #7361: Block users from entering date out of range\"",
"tree": {
"sha": …
```

Fixes error resolving collaboration commit author in edge cases

---

lib/api.ts

Cache computed values to reduce build times

---

public/favicon.ico
public/logo.webp

- fixes #385
The issue was here at symlink
The both `favicon` and `logo.webp` were pointing to wrong location.
```➜  public git:(main) l 
total 12K
drwxrwxr-x  3 mrsp mrsp 4.0K Mar 18 11:34 .
drwxrwxr-x 14 mrsp mrsp 4.0K Mar 18 11:34 ..
lrwxrwxrwx  1 mrsp mrsp   35 Mar 18 11:34 favicon.ico -> data-repo/config/assets/favicon.ico
drwxrwxr-x  6 mrsp mrsp 4.0K Mar 18 11:34 images
lrwxrwxrwx  1 mrsp mrsp   33 Mar 18 11:34 logo.webp -> data-repo/config/assets/logo.webp
```
```
lrwxrwxrwx  1 mrsp mrsp   38 Mar 18 12:17 favicon.ico -> ../data-repo/config/assets/favicon.ico
drwxrwxr-x  6 mrsp mrsp 4.0K Mar 11 19:10 images
lrwxrwxrwx  1 mrsp mrsp   36 Mar 18 12:16 logo.webp -> ../data-repo/config/assets/logo.webp
```

fix for organisation logo and favicon

---

config/GraduateAttributes.ts

Fixes issue with current level resolver for graduate attributes taking first level automatically if none achieved.
**Before:**
**After:**
cc: @bodhish

Fixes issue with current level resolver for GA if not achieved

---

components/navbar/Logo.tsx
components/navbar/Navbar.tsx

Now highlights selected item in nav bar in both dark, light mode. Small and Large screen.

Nav bar item highlight feature added | issue #378

---

lib/api.ts
public/.gitignore
scripts/generateNewContributors.js
scripts/pullHistoricalGitHubActivities.js
tsconfig.json

Populating the data repo with historical data involves two steps:
Run the following script by pointing to the data repository directory:
```bash
DATA_REPO=<data-repo-path> GITHUB_ORG=<org> GITHUB_TOKEN=<gh_pat> node scripts/pullHistoricalGitHubActivities.js
```
```bash
DATA_REPO=<data-repo-path> GITHUB_TOKEN=<gh_pat> node scripts/generateNewContributors.js
```
https://github.com/coronasafe/leaderboard-data/pull/36
cc: @bodhish

Adds script for pulling historical data for an org.

---

app/people/_components/ContributorPage.tsx
app/people/_components/HoverCardWrapper.tsx
app/people/_components/HoverInfocard.tsx

closes #421 
- dynamically imported HoverCard
- made a wrapper to dynamically import
tested on wsl2 in development and production

refactor: implemented dynamic import on /people route

---

components/filters/Search.tsx

This pr fixes allignment of search icon in `Serachbar.tsx`
**Fixes : ** #435 
1. Desktop View
2. Mobile view

Fixes allignment of search icon

---

app/projects/constants.ts

- Added a hover effect to the "Google Summer of Code" label.
- On hover, the background color changes to yellow and the text color turns white.
**Details:**
- Updated the `ACTIVE_PROJECT_LABELS` configuration with a new `className` to include the hover effect.
- Utilized Tailwind CSS utility classes: `hover:bg-yellow-500`, `hover:text-white`.
**Before:**
- The label had a static background and text color.
**After:**
- The background now turns yellow and the text color changes to white on hover.

Added hover Effect in Google Summer of Code label

---

scraper/src/github-scraper/parseEvents.ts

- https://github.com/ohcnetwork/leaderboard/pull/512
`pr_merged` events was using the event actor (in this case the one who merged the PR). However, in leaderboard `pr_merged` events are associated to the PR authors for incentivizing the contributor.
Regression from recent scraper refactor from python to typescript

Fixes #503; Correct event owner for `pr_merged` events

---

app/people/page.tsx
next-env.d.ts

This PR fixes the issue where the "Still waiting for this" message was being displayed on the people page when there was no content. Now, if there's no valid content, nothing will be shown instead.
Fixes #498

fix: Show nothing instead of 'Still waiting for this' on people page #498

---

components/contributors/BadgeIcons.tsx

Fix #516 : Make contributor badges theme aware 
- Updated the badge component to reflect proper styling based on the selected theme (light or dark mode).
- Adjusted color contrast to ensure readability and consistency across themes.
- Applied theme-specific background and text color changes to improve the user experience when hovering over the contributor badges.
- Ensured the hover effect and other dynamic styles are responsive to theme changes.
PR Description:
This PR addresses issue #516, where the contributor badges were not theme aware. The badges had a dark UI component, regardless of the selected theme, leading to a lack of contrast and consistency in light mode.
Changes:
Modified the badge component to apply theme-specific styles dynamically for both light and dark modes.
Ensured …

Make Contributor Badges Theme Aware

---

components/RelativeTime.tsx
components/contributors/BadgeIcons.tsx

Fix #422 
The `RelativeTime` component displayed incorrect relative time when rendered on statically generated routes since it was computed server-side and did not update based on the client's time.
- Refactored the `RelativeTime` component to compute the relative time on the client side.
- Added the `"use client"` directive to ensure that the component runs entirely on the client side.
- Implemented `useEffect` and `useState` to calculate and update relative time every minute dynamically.
- Ensured the text representation of relative time is accurate on client-side rendering, fixing the issue of stale time displays on static pages.
This update addresses the problem by making the relative time always reflect the current time on the client side, providing an accurate user experience.

Fix client-side relative time calculation for statically generated routes ..

---

components/contributors/ContributorImage.tsx
components/contributors/InfoCard.tsx
components/contributors/LeaderboardCard.tsx

**Overview**:  
This PR introduces a **reusable component** for displaying contributor images in different sizes (small, medium, large) and adds styling for the top 3 contributors in the leaderboard.
**Changes Made**:
1. Created a reusable `ContributorImage` component with support for:
- **Small**: For feed titles.
- **Medium**: For the leaderboard.
- **Large**: For profiles and home route.
2. **Leaderboard Styling**:
- **Top 3 contributors**: Rank 1 (yellow), Rank 2 (gray), Rank 3 (amber).
- **Others**: Purple border for all non-ranked contributors.
3. Replaced all instances of contributor images across the codebase with the new component.
---
If I missed anything, please feel free to address here.
Thank you.

Created reusable component for contributors Avatar

---

app/leaderboard/[duration]/Leaderboard.tsx

- feat(leaderboard): add filtering, sorting, and search functionality in query params
Fix for #526

feat(leaderboard): add filtering, sorting, and search functionality in query params

---

app/leaderboard/[duration]/Leaderboard.tsx
lib/api.ts
lib/types.ts
scraper/src/github-scraper/types.ts

Added a new statistics section between filters and leaderboard that displays:
- Total Issues Opened/Closed
- Total PRs Opened/Merged
- Color-coded icons for each metric
> ☝🏼 wrote by cursor

Add Statistics Summary Cards to Leaderboard

---

scraper/src/github-scraper/projectItems.ts

- Project board cached items are now unique for each item and contributor. This allows filtering through flatgithub explorer much easily.
- Also tagged by `completedAtMonth` to ease filtering contributions closed (as completed)/merged in the month.
- Fixes https://github.com/ohcnetwork/leaderboard-data/issues/71

Update project board script to treat contributors as first class citizens of the cache

---

app/leaderboard/[duration]/Leaderboard.tsx

Made Filters display Properly on Mobile View in Leaderboard Page

---

components/contributors/BadgeIcons.tsx

Fixes [#586](https://github.com/ohcnetwork/leaderboard/issues/586)
Previous:
Now:

Fix Badge modal responsiveness

---

components/gh_events/GitHubEvent.tsx

Fixes #593 
- Adds relative time in the title for `PushEvent` type events on feed page
Before
After

Add relative time for push event on feed page
