contributors/ishanExtreme.md

My Twitter and LinkedIn username was incorrect in the MD file so I fixed it to the correct one.

IshanExtreme's linkedin and twitter url fixed

---

components/contributors/TopContributor.jsx

Responsive alignment for InfoCard Content

---

pages/contributors/[slug].js

Hides "currently working on" if data is empty

---

components/contributors/GithubActivity.jsx

Format activity time

---

pages/contributors/[slug].js

Closes #18 
https://user-images.githubusercontent.com/25143503/170851623-abbe7455-0b87-4350-bcd6-4c519b1e3d2c.mp4

Fix activity card being hidden in `md` sizes

---

contributors/GokulramGHV.md
lib/markdownToHtml.js
package.json
pages/contributors/[slug].js
tailwind.config.js
yarn.lock

Fixes #1 
The support for markdown rendering for user bio is implemented.
Preview:

Markdown functionality for contributor bio

---

components/contributors/InfoCard.jsx
components/contributors/LeaderboardCard.jsx
components/contributors/TopContributor.jsx
next.config.js
pages/leaderboard.js

- Fix the background and foreground contrast ratio on some pages
- Fix aria-role tags
- Remove unused imports on leaderboard
- Replace `img` tag with `next/image`
- Set lang as en
**Improved accessibility score to 100 with lighthouse**

Improve Accessibility

---

contributors/rithviknishad.md

Updates `rithviknishad`'s bio

---

contributors/arpancodes.md
contributors/developedBySJ.md
contributors/khavinshankar.md

Added Contributors

---

.github/workflows/main.yml

change cron time to every 12 hours

---

config/GraduateAttributes.js
lib/api.js
scraper/src/github.py

Fixes #67 
When multiple users committed on same pr or when multiple users co-author a commit, each user gets points for collaboration.

Added support for collaboration achievement

---

components/contributors/InfoCard.jsx
components/contributors/LeaderboardCard.jsx
components/filters/Filters.jsx
package.json
pages/contributors/[slug].js
pages/leaderboard.js
scraper/src/github.py
yarn.lock

Fixes #87 
- Added 2 extra fields in open_prs (`stale_for`, `labels`)
- Show yellow blinking dot in the InfoCard if the user has stale prs
- Show stale prs in a dimmer color

Add support for identifying stale prs

---

pages/index.js

Fixes #91 
Enhanced the hover effect

Added hover effect on leaderboard

---

components/PageHead.jsx
pages/_app.js
pages/contributors/[slug].js
pages/index.js

Preview images for links

---

pages/index.js

Added responsiveness

---

.github/workflows/main.yml

Closes #106 
Wraps the scrapper step with [Retry Step](https://github.com/marketplace/actions/retry-step) GH Action

retry scrapper if failed

---

.github/workflows/main.yml
scraper/src/github.py

Update to use `GIT_ACCESS_TOKEN` + wrap fetchs with try catch

---

data/github/GokulramGHV.json
data/github/aparnacoronasafe.json
data/github/cp-Coder.json
data/github/khavinshankar.json
data/github/nihal467.json
data/github/patelaryan7751.json
data/github/rabilrbl.json
data/github/rithviknishad.json
data/github/siddnikh.json
data/github/siva-balan.json

Ran `python scraper/src/github.py coronasafe data/github -n 10`
<details>
<summary>Log</summary>
```
2023-02-07 22:22:59,353 [DEBUG] - Fetching events for coronasafe from 2023-01-27 to 2023-02-06
2023-02-07 22:22:59,353 [INFO] - Scraping coronasafe
2023-02-07 22:22:59,353 [INFO] - Fetching events page:1
2023-02-07 22:23:00,838 [INFO] - Fetched 0 events
2023-02-07 22:23:00,838 [INFO] - Fetching events page:2
2023-02-07 22:23:02,530 [DEBUG] - Parsing event for nihal467
2023-02-07 22:23:02,530 [DEBUG] - event_id: 26906379751
2023-02-07 22:23:02,531 [DEBUG] - Appending event for nihal467
2023-02-07 22:23:02,531 [DEBUG] - Adding new user nihal467
2023-02-07 22:23:02,531 [DEBUG] - Parsing event for nihal467
2023-02-07 22:23:02,531 [DEBUG] - event_id: 26906130714
2023-02-07 22:23:02,531 [DEBUG] …
```

Run github scrapper for last 10 days (Feb 7)

---

.gitignore
.yarnrc.yml
pages/contributors/[slug].js

Adds `repo/pr` prefix for currently working on

---

pages/leaderboard.js

sort by points if category points same

---

app/contributors/[slug]/page.tsx
components/contributors/GithubActivity.tsx
lib/types.ts
lib/utils.ts
package.json
pnpm-lock.yaml
scraper/src/github.py

added turnaround time for merged prs

---

components/gh_events/GitHubEvents.tsx
lib/gh_events.ts

Combines similar push events

---

app/feed/FeedPagination.tsx
app/feed/layout.tsx
app/feed/page.tsx
app/page.tsx
components/gh_events/GitHubEvent.tsx
lib/gh_events.ts

Add Feed Page (SSR)

---

app/contributors/[slug]/page.tsx
app/globals.css

Remove journey map

---

app/contributors/[slug]/page.tsx
lib/api.ts

Add metrics on contributors page

---

app/contributors/[slug]/page.tsx
components/Markdown.tsx

Fix Markdown not being rendered

---

components/contributors/GithubActivity.tsx

- Fixes #188 
- Change the look of the PR Collaboration

Fix the look of PR Collaboration

---

.gitignore
.husky/pre-commit
.lintstagedrc.js
README.md
components/gh_events/GitHubEvent.tsx
components/gh_events/OpenGraphImage.tsx
components/gh_events/ReleaseEventBody.tsx
package.json
pnpm-lock.yaml

**Proposed Changes**
- Fixes #195 
- Added pre-commit hook

Add pre commit hook

---

app/contributors/[slug]/page.tsx

show 404 for invalid user instead of erroring to 500

---

components/contributors/TopContributor.tsx

fixed center allignment when multiple contributors are listed in top contributors card.

---

app/contributors/[slug]/page.tsx
app/globals.css
app/leaderboard/Leaderboard.tsx
app/page.tsx
components/DateRangePicker.tsx
components/Header.tsx
components/LoadingText.tsx
components/Markdown.tsx
components/contributors/GithubActivity.tsx
components/contributors/LeaderboardCard.tsx
components/contributors/TopContributor.tsx
components/gh_events/GitHubEvent.tsx
lib/utils.ts

- fixes #213
- fixed some other minor spacing and alignment issues
cc: @bodhish

Use monospaced font

---

components/contributors/GithubActivity.tsx

fixes improper sorting of slack activities

---

.env
components/contributors/InfoCard.tsx

Show slack icon on contributors social list

---

app/contributors/[slug]/page.tsx

Show update profile button on contributors profile

---

components/contributors/GithubActivity.tsx

Show activity count of each activity type in filters

---

app/contributors/[slug]/page.tsx
app/page.tsx
app/people/page.tsx
components/contributors/GithubActivity.tsx
lib/api.ts
lib/types.ts
load-fixtures.sh

Adds gallery view of contributors (`/people`) and minor fixes

---

.github/workflows/scraper-preview.yaml

Adds workflow to test run github scraper on pull requests

---

components/contributors/GithubActivity.tsx

fixes absolute date range pagination not working in contributors activity timeline

---

app/api/leaderboard/functions.ts
app/api/leaderboard/route.ts
app/leaderboard/Leaderboard.tsx
app/leaderboard/page.tsx
components/DateRangePicker.tsx
components/Select.tsx
components/filters/RoleFilter.tsx
components/filters/Sort.tsx

Fixes issue #231 
- implemented sort by role 
[Screencast from 25-02-24 05:14:58 PM IST.webm](https://github.com/coronasafe/leaderboard/assets/111575806/700eb731-e593-466a-980f-ff83295b7fab)

select filter for leaderboard contributors role

---

components/Header.tsx
lib/utils.ts

Adding a navabar feature
Fixes #246 
Please delete options that are not relevant.

adding navbar feature

---

app/api/leaderboard/functions.ts
app/projects/ActiveProjects.tsx
app/releases/Releases.tsx
components/releases/ReleaseSection.tsx
lib/getGitHubAccessToken.ts

- Fixes `GITHUB_PAT` not configured error in local development
- Refactored error handling of missing `GITHUB_PAT` env in local development as a reusable function

Fixes `GITHUB_PAT` not configured error in local development

---

scripts/slackEODReminder.js

- Part of #269
- Adds support for reporting review events (distinct on PR)

Slack EOD Reminder: Adds support for reporting review events

---

app/leaderboard/_components/Searchbar.tsx
app/page.tsx
components/DateRangePicker.tsx
components/Header.tsx
components/LoadingText.tsx
components/contributors/GithubActivity.tsx

- Fixed Incorrect background in home page Leaderboard section
- Search bar ui improvements
- Theme switch improvement in mobile view
- Imporved loading screen for mobile view
- made contributors page responsive

UI improvements

---

README.md
app/api/leaderboard/functions.ts
lib/types.ts
scripts/generateMD.js
scripts/generateNewContributors.js
scripts/migrateExistingMD.js
scripts/migrations/001_migrate_role_to_single_field.js

Fixes #271
linked pr https://github.com/coronasafe/leaderboard-data/pull/17

update user role field to be single role 

---

app/leaderboard/_components/Leaderboard.tsx

Improves top contributors display logic

---

components/DateRangePicker.tsx

Added indication for option selected in Date Range picker

---

components/contributors/BadgeIcons.tsx

<h1 align="center">fixes #299 </h1>

solving the layout issue of Image

---

.env
README.md
app/leaderboard/_components/LeaderboardWrapper.tsx
app/leaderboard/_components/Searchbar.tsx
app/page.tsx
env.mjs
lib/const.ts

Changes Default Values of Roles for Initial Page Load on Leaderboard Page 

---

app/leaderboard/_components/Searchbar.tsx
components/filters/Search.tsx
package.json
pnpm-lock.yaml

#323 
- new dependency "use-debounce"
- added defaultValue to Search component
- debounces search with 300ms delay
Development: success
Production: success
(using WSL2)

refactor: added debounce to search

---

components/contributors/BadgeIcons.tsx

- Fixes #318 
- changed z-index of badges to be lower than navbar

changed z-index of badge to not clash with navbar

---

app/page.tsx
components/navbar/Navbar.tsx

Fix overflow in home at 1280px

---

app/api/contributors/[slug]/dailyReport/route.ts
app/api/leaderboard/functions.ts
app/projects/ActiveProjects.tsx
lib/octokit.ts

- Fixes #328
- Adds API route: `GET /api/contributors/[github_username]/dailyReport`
- Revalidates at-most once every 15 mins per contributor.
<details>
<summary>Example Response</summary>
```json
{
"pull_requests": [
{
"title": "Adds API for contributor daily reports",
"url": "https://github.com/coronasafe/leaderboard/pull/339"
},
{
"title": "Explicitly specify revalidate duration",
"url": "https://github.com/coronasafe/leaderboard/pull/332"
}
],
"commits": [
{
"title": "adds missing shebang to `load-org-data`",
"url": "https://github.com/coronasafe/leaderboard/commit/c9076d550ed42883396ba6ba4e9ec51a71a4978e"
}
],
"reviews": [
{
"state": "APPROVED",
"pull_request": "Fix overflow in home at 1280px",
"url": "https://github.com/coronasafe/leaderboard/pull/337#pullrequestreview-1916394927" …
```

Adds API for contributor daily reports

---

app/contributors/[slug]/page.tsx
components/contributors/GithubActivity.tsx
lib/api.ts
lib/types.ts
scraper/src/github.py
scripts/migrations/002_migrate_github_activity_timestamps.js

- Updates scraper to serialize ISO8061 timestamp for GitHub activities and `last_updated`
- Adds script to migrate existing data

Update scraper to serialize ISO8061 timestamp and adds script to migrate existing data

---

app/contributors/[slug]/page.tsx
components/contributors/BadgeIcons.tsx

Update badges overflow closes #344

---

components/releases/ReleaseSection.tsx

Update margin for timeline closes #357

---

components/navbar/Navbar.tsx

Update Navbar styling for readability closes #359

---

app/projects/ActiveProjects.tsx
lib/octokit.ts
package.json
pnpm-lock.yaml

closes #345 
- added "server-only" to lib/octokit.ts
- migrated fetch to octokit in projects/ActiveProject
- removed labelsFilter (not needed in octokit)
tested in production and development

refactor: migrated projects/ActiveProject.tsx to use octokit

---

app/projects/ActiveProjects.tsx
app/projects/constants.ts

fixed Broken responsiveness for Active Projects page in mobile view

---

app/api/leaderboard/functions.ts
app/releases/layout.tsx
app/releases/page.tsx
components/Markdown.tsx
components/releases/ReleaseSection.tsx
lib/types.ts

- closes #358 
- if width is above 390px the care/org is shown
- if width is below 390px it is hidden

Enhance Release Event Card for Mobile View closes #358

---

components/contributors/GithubActivity.tsx

Fixes - #377 
- Changed from using Link to anchor tags , since those are not used for client side navigation and are external links, and would be better if they open in new tab by default

Added hyperlink for comments, and changed from using Link to anchor tag

---

app/contributors/[slug]/page.tsx

- fixes #364 
[Screencast from 13-03-24 06:11:23 PM IST.webm](https://github.com/coronasafe/leaderboard/assets/72642534/1319ccd9-290f-4790-ae7e-46d32631eb44)

fixing profile section overflow issue

---

app/api/task/complete/route.ts
app/api/task/create/route.ts
app/api/task/delete/route.ts
app/api/task/list/route.ts
app/api/task/slack.ts
app/api/task/task.ts
package.json
pnpm-lock.yaml

- Implements API endpoints required for basic CRUD operations for managing tasks from Slack Bot
- Uses Vercel's KV Redis Storage for storing the tasks for each slack user
https://github.com/coronasafe/leaderboard/assets/25143503/94f8a3e3-a5a9-4a46-89af-c56e48597128

Implement API endpoints for tasks bot slack app

---

README.md
app/page.tsx
components/gh_events/GitHubEvent.tsx

update show more contributors link

---

app/contributors/[slug]/page.tsx

Beta header removed from the contributor's profile page.
Fixes #399

remove beta header

---

app/contributors/[slug]/page.tsx

There is no more extra scroll bar in cotrbutor's profile.
Fixes #400

extra scrollbar removed from cotributor's profile

---

app/contributors/[slug]/page.tsx
components/DateRangePicker.tsx
components/contributors/GithubActivity.tsx

Closes #294 
1. I have commented previous code for filtering. 
2. Used DateRangePicker component which was used in leaderboard for filtering. 
3. Ensured responsiveness across various screen sizes.

Custom date range filter implemented in Contributor Activity (#294)

---

app/issues/page.tsx
app/projects/constants.ts
components/navbar/Navbar.tsx

This PR is for adding a new `Issue` page. Which contains `good first issues` across all repositories for new contrbutors.
Fixes #426
1. Created a New issue page.
2. Use `ActiveProject.tsx `component

Issue page

---

app/api/slack-eod-bot/route.ts

Fixed Slack Events Duplicates

---

lib/contributor.ts
lib/slackbotutils.ts

EOD Bot : Showing cached app home for one hour

---

lib/slackbotutils.ts

Ref: https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#opting-out-of-data-caching

Slack EOD Bot: Ensure postMessage's are not cached

---

activities-bot/src/sendReminder.mjs
activities-bot/src/utils.mjs

EOD Reminders: Adds support for retries

---

app/contributors/[slug]/page.tsx
pnpm-lock.yaml

This pull request aims to enhance the profile page title and meta description for better clarity and SEO. The title now includes the contributor's full name and the organization name, and the description summarizes the contributor's activity and joining date.
This pull request addresses issue  [465](https://github.com/coronasafe/leaderboard/issues/465)
1. **Title Update:**
- The profile page title is now set to `{contributor.name} | {org}`, providing a clearer and more informative title.
- Example: "Rithvik Nishad | Open Healthcare Network"
2. **Meta Description:**
- The meta description now summarizes the contributor's activity and joining date.
- Example: "Rithvik Nishad has opened 123 pull requests so far since June 2022 at Open Healthcare Network"

Improved page title and description

---

.env
components/Footer.tsx
env.mjs
package.json
pnpm-lock.yaml

**Resolves #436**
This pull request updates the footer component to include:
- **Organization Logo**: Maintains brand recognition.
- **Data Repository Link**: Direct access to datasets and resources.
- **Flat Repository Explorer Link**: Efficient navigation of repositories.
- **Social Media Links**: Connects users with organizational profiles.
- **Contact Information**: Provides an email address or contact form for inquiries.
- `NEXT_PUBLIC_FLAT_REPO_EXPLORER_URL`
- `NEXT_PUBLIC_DATA_SOURCE`
- `NEXT_PUBLIC_GITHUB_URL`
- `NEXT_PUBLIC_LINKEDIN_URL`
- `NEXT_PUBLIC_YOUTUBE_URL`
- `NEXT_PUBLIC_CONTACT_EMAIL`
- Verified that new footer elements are displayed correctly.
- Ensured that links and contact information are functional.

Redesigned Footer

---

components/Footer.tsx

FIXED #478 
Improved the footer Design

New footer design

---

components/contributors/InfoCard.tsx

Changes Made
Updated the InfoCard.tsx component to replace the Social app's logo with the corresponding icon from the react-icon package.
Ensured compatibility across different browsers and devices.
Before:
After:

Updated Social Icons in Contributors Section

---

components/Footer.tsx
env.mjs
lib/discussion.ts

- Added support for showing social icons in footer only if env value is defined.
- Added support for showing twitter X social icon in footer.
- Resolves #480

Adds support for X logo in org. socials and hide undefined social URLs

---

scraper/src/github-scraper/index.ts

Scraper: Fixes incorrect default date range

---

scraper/src/github-scraper/saveData.ts

Scraper: Deduplicate user activities before writing the data

---

scraper/src/github-scraper/parseEvents.ts

fix: Skip merge commit authors from being included in PR collaborators

---

app/leaderboard/[duration]/Leaderboard.tsx

- Fix (LeaderBoard) filter points bug fixed
- Handled on points change updated the state based on applied filter
- related to #529

Fix (LeaderBoard) filter points bug fixed

---

scraper/src/github-scraper/parseEvents.ts

Gracefully handle PR events for potentially deleted contributor

---

components/contributors/LeaderboardCard.tsx

Fix: clipping out contributor card

---

components/navbar/Navbar.tsx

Missing Active Effect on Leaderboard Tab

---

app/contributors/[slug]/page.tsx

Fix: Message on contributor profile to update bio

---

app/discussions/layout.tsx
app/people/page.tsx
app/releases/page.tsx

Fixes minor spacing issues and spelling  in discussion page

---

app/leaderboard/[duration]/Leaderboard.tsx

- Fixes #583 
- Fixed the PR merge icon in leaderboard page

PR Merge Icon corrected

---

components/contributors/LeaderboardCard.tsx

Fixes #561 
old version
updated version

FIXED: Leaderboard list responsivness

---

app/leaderboard/[duration]/Leaderboard.tsx
components/contributors/TopContributor.tsx

Fixes #606 
**UI AFTER CHANGES**
https://github.com/user-attachments/assets/09004cdb-69a7-456a-8c42-db3c391fd02c

Display Stats For Top Contributors and Fix Typo

---

app/people/page.tsx

Fixed padding for mobile view in contributors page

---

app/contributors/[slug]/page.tsx
app/posters/page.tsx
components/contributors/GithubActivityCompact.tsx

fix: https://github.com/ohcnetwork/leaderboard/issues/617

New GitHub activity compact
